CREATE TABLE `hackathon_feedback` (
	`id` text PRIMARY KEY NOT NULL,
	`hackathon_id` text NOT NULL,
	`food_rating` integer NOT NULL,
	`staff_rating` integer NOT NULL,
	`organization_rating` integer NOT NULL,
	`platform_rating` integer NOT NULL,
	`judges_rating` integer NOT NULL,
	`venue_rating` integer NOT NULL,
	`participants_community_rating` integer NOT NULL,
	`communication_before_rating` integer NOT NULL,
	`communication_during_rating` integer NOT NULL,
	`rules_fairness_rating` integer NOT NULL,
	`overall_experience_rating` integer NOT NULL,
	`schedule_pacing_rating` integer NOT NULL,
	`technical_setup_rating` integer NOT NULL,
	`safety_accessibility_inclusion_rating` integer NOT NULL,
	`outcomes_rating` integer NOT NULL,
	`comment` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CHECK (`food_rating` >= 1 and `food_rating` <= 5),
	CHECK (`staff_rating` >= 1 and `staff_rating` <= 5),
	CHECK (`organization_rating` >= 1 and `organization_rating` <= 5),
	CHECK (`platform_rating` >= 1 and `platform_rating` <= 5),
	CHECK (`judges_rating` >= 1 and `judges_rating` <= 5),
	CHECK (`venue_rating` >= 1 and `venue_rating` <= 5),
	CHECK (`participants_community_rating` >= 1 and `participants_community_rating` <= 5),
	CHECK (`communication_before_rating` >= 1 and `communication_before_rating` <= 5),
	CHECK (`communication_during_rating` >= 1 and `communication_during_rating` <= 5),
	CHECK (`rules_fairness_rating` >= 1 and `rules_fairness_rating` <= 5),
	CHECK (`overall_experience_rating` >= 1 and `overall_experience_rating` <= 5),
	CHECK (`schedule_pacing_rating` >= 1 and `schedule_pacing_rating` <= 5),
	CHECK (`technical_setup_rating` >= 1 and `technical_setup_rating` <= 5),
	CHECK (`safety_accessibility_inclusion_rating` >= 1 and `safety_accessibility_inclusion_rating` <= 5),
	CHECK (`outcomes_rating` >= 1 and `outcomes_rating` <= 5),
	FOREIGN KEY (`hackathon_id`) REFERENCES `hackathons`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `hackathon_feedback_hackathon_created_idx`
ON `hackathon_feedback` (`hackathon_id`, `created_at`);
